### PR TITLE
ci(cirrus): use cirrus-ci alongisde travis-ci

### PR DESCRIPTION
**Pull request by myii**
* Based on response from Cirrus CI:
  - https://github.com/fkorotkov/nginx-formula/pull/1

### CODE REVIEW

**Comment by myii** [comment]
OK, we've got to wait until Cirrus CI is enabled for this repo...

**Comment by javierbertoli** [comment]
Thanks for all this effort, @myii :beer:

**Comment by myii** [comment]
Just a note for posterity, we enabled all 15 instances in the matrix for initial testing.  We'll reduce back to the 5/6 after a short while.

Thanks for the merge @javierbertoli!

**Comment by aboe76** [comment]
This cirrus ci, looks good, clean interface @myii how do you like it so far?

**Comment by myii** [comment]
@aboe76 I'm liking it, maybe for the wrong reasons so far!  Once we get a few out there and we gain the concurrency benefits, I think I'm going to like it for the right reasons.

By the way, I've just added another Cirrus PR here: https://github.com/saltstack-formulas/syslog-ng-formula/pull/15.  Would you mind merging it when the tests complete?

**Pull request merged**
