### PR TITLE
Implement an automated changelog

### PR DESCRIPTION
**Pull request by n-rodriguez**
Inspired by https://github.com/saltstack-formulas/collectd-formula/pull/139

### CODE REVIEW

**Comment by myii** [comment]
@n-rodriguez Thanks for this PR.  I've tested it in my own fork and it appears to be working fine.  There are just a few minor changes I'd request.

- [x] Fix the non-conforming commit message.
    * I.e. `Update README`.
    * Probably better to squash into the one commit.
- [x] Update the `README` to show the badges and include the related information, as shown in [this diff](https://github.com/saltstack-formulas/chrony-formula/pull/17/files#diff-8ab5636c6c18641e5c58358ef489e0f7R1).
- [x] Use `commitlint.config.js` identical to upstream.
    * Whitespace is different.
- [x] Use `release.config.js` identical to upstream.
    * Whitespace is different.
    * The amount of change here showed up as different sections in `meld`.
    * Becomes difficult to confirm everything is OK.
    * Will be difficult to maintain if changes are ever needed to be propagated across all formulas.

**Review by myii — CHANGES_REQUESTED** [review]
As mentioned in my comment.

**Comment by n-rodriguez** [comment]
@myii done!

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
Merged this excellent PR, @n-rodriguez!

**Comment by n-rodriguez** [comment]
One more question : the link to the contribute page is broken : 

```
:ref:`How to contribute <CONTRIBUTING>` 
```

**Comment by myii** [comment]
@n-rodriguez The explanation about this is here: https://template-formula.readthedocs.io/en/latest/README.html#contributing-to-this-repo.

Basically, it's a Sphinx link that works on Read the Docs.  The original plan was to automatically prepare documentation for each formula there.  However, that's changed a little since then and all of these documentation files will be centralised instead, rather than repeat identical content in 300+ `README` files!  So it's a little ugly for the time being, until we can get to that solution.

**Comment by n-rodriguez** [comment]
ok! thank you!

**Pull request merged**
